name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build with Buildozer
        uses: kivy/buildozer-action@master
        with:
          buildozer_version: stable
